# Generated by Django 2.2 on 2021-09-15 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fav_books_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user_uploads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_uploaded', to='login_and_reg_app.User'),
        ),
        migrations.AlterField(
            model_name='book',
            name='users_liked',
            field=models.ManyToManyField(related_name='liked_books', to='login_and_reg_app.User'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
