# Generated by Django 2.2 on 2021-09-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_reg_app', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagepost',
            name='poster',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='MessagePost',
        ),
    ]
